version: '3'

services:
  inkydocker:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./images:/app/images
    restart: unless-stopped
    environment:
      - TZ=Europe/Copenhagen